version: '3'
services:
    app:
        restart: always
        image: nginx:1.19
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www
        expose:
            - "80"
